export const ADD_NOTE = 'ADD_NOTE'
export const DELETE_NOTE = 'DELETE_NOTE'
export const SHOW_NOTE = 'SHOW_NOTE'
//export const MODIFY_NOTE = 'MODIFY_NOTE'
//export const SAVE_NOTE = 'SAVE_NOTE'
export const SHOW_LAYER = 'SHOW_LAYER'
export const SHOW_EDITER = 'SHOW_EDITER'